AWSTemplateFormatVersion: '2010-09-09'
Description: Resources related to the AWS ECR
Parameters:
  RepositoryName:
    Type: String
Resources:
  GotApiTypesEcrRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId' , ':root'] ]
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'