AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Resources for automated deployment of all gothub components
Resources:
  DeployUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: 'AmazonEC2ContainerRegistryPutImage'
        PolicyDocument: 
          Version: '2012-10-17'
          Statement: 
            - Effect: 'Allow'
              Action:
                - 'ecr:PutImage'
                - 'ecr:GetAuthorizationToken'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:InitiateLayerUpload'
                - 'ecr:UploadLayerPart'
                - 'ecr:CompleteLayerUpload'
                - 'ecr:GetDownloadUrlForLayer'
              Resource: '*'
      - PolicyName: 'AmazonEC2ContainerServiceDeployment'
        PolicyDocument: 
          Version: '2012-10-17'
          Statement: 
            - Effect: 'Allow'
              Action:
                - 'ecs:UpdateService'
              Resource: '*'