AWSTemplateFormatVersion: '2010-09-09'
Description: Resource assets for the got-api-types service to run its functionality
Parameters:
  ApiTypesS3BucketName:
    Type: String
    Default: "gothub-types-dev"
    Description: "S3 bucket name"
Resources:
  ApiTypesS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref "ApiTypesS3BucketName"
      VersioningConfiguration:
        Status: Enabled
  ApiTypesTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
