AWSTemplateFormatVersion: '2010-09-09'
Description: Resource assets for the got-api-types service to run its functionality
Parameters:
  GotHubUiS3BucketName:
    Type: String
    Default: "gothub-ui-dev"
    Description: "S3 bucket name"
  CorsAllowedOrigins:
    Type: String
    Default: "*"
    Description: "Allowed origins for S3 resource GET"
Resources:
  GotHubUiS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref "GotHubUiS3BucketName"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['Authorization']
            AllowedMethods: [GET]
            AllowedOrigins: [{ "Ref" : "CorsAllowedOrigins" }]
            MaxAge: '3000'
  GotHubUiS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: "GotHubUiS3Bucket"
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": {"Fn::Join" : [ "", [ "arn:aws:s3:::", { "Ref" : "GotHubUiS3BucketName" }, "/*" ] ]}
            }
          ]
        }
